"""Typed event definitions for the Ciicerone shared event bus.

These event types are used by the exercise orchestrator and color teams to
communicate during a simulation. Each event carries a tenant-scoped payload
with enough context for audit, replay, and downstream analytics.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4


class EventType(str, Enum):
    """Canonical event types published on the shared event bus."""

    # Simulation lifecycle
    SIMULATION_STARTED = "simulation.started"
    SIMULATION_COMPLETED = "simulation.completed"
    SIMULATION_FAILED = "simulation.failed"
    STAGE_STARTED = "stage.started"
    STAGE_COMPLETED = "stage.completed"
    STAGE_FAILED = "stage.failed"

    # Red team
    RED_TEAM_ATTACK_STAGE = "red_team.attack_stage"
    RED_TEAM_IOC_GENERATED = "red_team.ioc_generated"

    # Blue team
    BLUE_TEAM_ALERT = "blue_team.alert"
    BLUE_TEAM_HUNT_EVENT = "blue_team.hunt_event"
    BLUE_TEAM_INCIDENT_CREATED = "blue_team.incident_created"

    # Purple / White / Black teams
    PURPLE_TEAM_AAR = "purple_team.aar"
    WHITE_TEAM_ROE_VIOLATION = "white_team.roe_violation"
    BLACK_TEAM_SCORE = "black_team.score"


@dataclass
class BusEvent:
    """Base class for all events published on the shared event bus.

    Attributes:
        event_type: Canonical event type from :class:`EventType`.
        tenant_id: Tenant scope for the event.
        exercise_id: Optional exercise identifier (UUID or string).
        simulation_id: Optional simulation identifier.
        timestamp: UTC datetime when the event was created.
        event_id: Unique event identifier.
        payload: Domain-specific event data.
    """

    event_type: EventType
    tenant_id: str
    exercise_id: Optional[str] = None
    simulation_id: Optional[str] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    event_id: str = field(default_factory=lambda: str(uuid4()))
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the event to a JSON-friendly dictionary."""
        return {
            "event_id": self.event_id,
            "event_type": self.event_type.value,
            "tenant_id": self.tenant_id,
            "exercise_id": self.exercise_id,
            "simulation_id": self.simulation_id,
            "timestamp": self.timestamp.isoformat(),
            "payload": self.payload,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BusEvent":
        """Reconstruct a BusEvent from a dictionary."""
        return cls(
            event_type=EventType(data["event_type"]),
            tenant_id=data["tenant_id"],
            exercise_id=data.get("exercise_id"),
            simulation_id=data.get("simulation_id"),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            event_id=data.get("event_id", str(uuid4())),
            payload=data.get("payload", {}),
        )


@dataclass
class RedTeamAttackStageEvent(BusEvent):
    """Red team attack stage event.

    Payload fields:
        stage_id: Unique stage identifier.
        stage_name: Human-readable stage name.
        technique_id: MITRE ATT&CK technique ID (e.g., T1566).
        tactic: MITRE ATT&CK tactic (e.g., initial_access).
        content: Attack content/log entry generated by the stage.
        target_system: Target system identifier.
        iocs: List of IOCs generated by the stage.
    """

    def __init__(
        self,
        tenant_id: str,
        stage_id: str,
        stage_name: str,
        technique_id: str,
        tactic: str,
        content: str,
        target_system: Optional[str] = None,
        iocs: Optional[List[str]] = None,
        exercise_id: Optional[str] = None,
        simulation_id: Optional[str] = None,
    ):
        super().__init__(
            event_type=EventType.RED_TEAM_ATTACK_STAGE,
            tenant_id=tenant_id,
            exercise_id=exercise_id,
            simulation_id=simulation_id,
            payload={
                "stage_id": stage_id,
                "stage_name": stage_name,
                "technique_id": technique_id,
                "tactic": tactic,
                "content": content,
                "target_system": target_system,
                "iocs": iocs or [],
            },
        )


@dataclass
class BlueTeamAlertEvent(BusEvent):
    """Blue team detection alert event.

    Payload fields:
        alert_id: Unique alert identifier.
        source_module: Module that generated the alert (siem, ids, edr, etc.).
        technique_id: MITRE ATT&CK technique ID detected.
        severity: Alert severity (critical, high, medium, low, info).
        description: Human-readable alert description.
        detected: Whether the attack stage was detected.
        response_time_ms: Time between attack stage and detection (if known).
        stage_id: Red team stage ID that triggered the alert (if matched).
        iocs: IOCs correlated with the alert.
        raw_data: Additional module-specific data.
    """

    def __init__(
        self,
        tenant_id: str,
        alert_id: str,
        source_module: str,
        technique_id: str,
        severity: str,
        description: str,
        detected: bool = True,
        response_time_ms: Optional[int] = None,
        stage_id: Optional[str] = None,
        iocs: Optional[List[str]] = None,
        raw_data: Optional[Dict[str, Any]] = None,
        exercise_id: Optional[str] = None,
        simulation_id: Optional[str] = None,
    ):
        super().__init__(
            event_type=EventType.BLUE_TEAM_ALERT,
            tenant_id=tenant_id,
            exercise_id=exercise_id,
            simulation_id=simulation_id,
            payload={
                "alert_id": alert_id,
                "source_module": source_module,
                "technique_id": technique_id,
                "severity": severity,
                "description": description,
                "detected": detected,
                "response_time_ms": response_time_ms,
                "stage_id": stage_id,
                "iocs": iocs or [],
                "raw_data": raw_data or {},
            },
        )


@dataclass
class BlueTeamHuntEvent(BusEvent):
    """Blue team threat hunting event.

    Payload fields:
        hypothesis_id: ID of the hunt hypothesis.
        technique_id: MITRE ATT&CK technique ID.
        confirmed: Whether the hypothesis was confirmed.
        findings: Summary of findings.
        iocs_found: IOCs discovered during the hunt.
    """

    def __init__(
        self,
        tenant_id: str,
        hypothesis_id: str,
        technique_id: str,
        confirmed: bool,
        findings: List[Dict[str, Any]],
        iocs_found: Optional[List[str]] = None,
        exercise_id: Optional[str] = None,
        simulation_id: Optional[str] = None,
    ):
        super().__init__(
            event_type=EventType.BLUE_TEAM_HUNT_EVENT,
            tenant_id=tenant_id,
            exercise_id=exercise_id,
            simulation_id=simulation_id,
            payload={
                "hypothesis_id": hypothesis_id,
                "technique_id": technique_id,
                "confirmed": confirmed,
                "findings": findings,
                "iocs_found": iocs_found or [],
            },
        )


@dataclass
class BlueTeamIncidentCreatedEvent(BusEvent):
    """Blue team incident created event.

    Payload fields:
        incident_id: ID of the created incident.
        title: Incident title.
        severity: Incident severity.
        category: Incident category.
        mitre_techniques: Related MITRE technique IDs.
    """

    def __init__(
        self,
        tenant_id: str,
        incident_id: str,
        title: str,
        severity: str,
        category: str,
        mitre_techniques: Optional[List[str]] = None,
        exercise_id: Optional[str] = None,
        simulation_id: Optional[str] = None,
    ):
        super().__init__(
            event_type=EventType.BLUE_TEAM_INCIDENT_CREATED,
            tenant_id=tenant_id,
            exercise_id=exercise_id,
            simulation_id=simulation_id,
            payload={
                "incident_id": incident_id,
                "title": title,
                "severity": severity,
                "category": category,
                "mitre_techniques": mitre_techniques or [],
            },
        )
